on:
  workflow_dispatch:
jobs:
  job1:
    name: uhmm
    runs-on: ubuntu-latest
    steps:
      - name: a
        run: |
          sudo apt update -y
          sudo apt install neofetch --no-install-suggests --no-install-recommends
          neofetch > out
      - name: b
        uses: actions/upload-artifact@v4
        with:
          path: ./out
