on:
  workflow_dispatch:
jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: a
        run: echo "hello" > out
      - name: b
        uses: actions/upload-artifact@v4
        with:
          path: ./out
